using UnityEngine;

public class Attack : MonoBehaviour
{
    public Vector2 knockback = Vector2.zero;
    public int attackDamage = 10;
 /*   Collider2D attackCollider;

    private void Awake()
    {
        attackCollider = GetComponent<Collider2D>();
    }
 */


    private void OnTriggerEnter2D(Collider2D collision)
    {
        //see if it can be hit
        Damageable damageable = collision.GetComponent<Damageable>();
        if(damageable != null)
        {
           Vector2 deliveredKnockback = transform.parent.localScale.x > 0 ? knockback : new Vector2(knockback.x * -1, knockback.y);
            bool gotHit = damageable.Hit(attackDamage, deliveredKnockback);


            if (gotHit) 
            { 
            Debug.Log(collision.name + "hit for " + attackDamage);
            }
        }
    }
}
